import type { Factor } from "./pure";

/**
 * Starting points for candidate places, rated 1 to 5 per factor. These are
 * Claude's rough 2026 impressions for two Americans with faith, a small
 * business, and a love of water, not measurements. Every card says so and
 * names what to check. Jen and John can add places and change any rating.
 */
export interface Place {
  key: string;
  name: string;
  kind: "country" | "state";
  line: string;
  ratings: Record<Factor, number>;
  fits: string;
  watch: string;
  /** The usual legal path for Americans, in one line. */
  path: string;
}

const r = (o: Partial<Record<Factor, number>>): Record<Factor, number> => ({
  cost: 3, safety: 3, faithCommunity: 3, religiousFreedom: 4, governmentReach: 3, transit: 3, healthcare: 3, language: 3, climate: 3, nature: 3, water: 3, family: 3, visaEase: 3, taxes: 3, internet: 4, work: 3, community: 3, pace: 3, housing: 3, food: 3,
  ...o,
});

export const PLACES: Place[] = [
  { key: "portugal", name: "Portugal", kind: "country", line: "Coast everywhere, slow, safe, and the easiest long-stay visa in Western Europe for Americans.", ratings: r({ cost: 4, safety: 5, faithCommunity: 3, religiousFreedom: 5, governmentReach: 3, transit: 4, healthcare: 4, language: 4, climate: 5, nature: 4, water: 5, family: 2, visaEase: 5, taxes: 3, internet: 4, work: 4, community: 4, pace: 5, housing: 3, food: 4 }), fits: "Water, pace, safety, and a visa (the D7 or D8) built for people with remote income.", watch: "Lisbon and the Algarve have gotten expensive; look at smaller coastal towns. Catholic culture, fewer evangelical churches outside cities. Bureaucracy is slow.", path: "D7 (passive income) or D8 (remote work) visa, then residency; apply through the Portuguese consulate." },
  { key: "spain", name: "Spain", kind: "country", line: "Big, varied, safe, with a remote-work visa and a lower cost of living outside the two big cities.", ratings: r({ cost: 4, safety: 5, faithCommunity: 3, religiousFreedom: 5, governmentReach: 3, transit: 5, healthcare: 4, language: 3, climate: 4, nature: 4, water: 4, family: 2, visaEase: 4, taxes: 2, internet: 4, work: 4, community: 4, pace: 4, housing: 3, food: 5 }), fits: "Trains, food, sun, and coast; the digital nomad visa is straightforward.", watch: "Spanish is needed outside tourist areas. Taxes on worldwide income once resident. Spain's wealth tax in some regions.", path: "Digital nomad visa or non-lucrative visa, applied for at a Spanish consulate." },
  { key: "italy", name: "Italy", kind: "country", line: "Beauty, faith history on every corner, and cheap living in the south and the villages.", ratings: r({ cost: 4, safety: 4, faithCommunity: 3, religiousFreedom: 5, governmentReach: 3, transit: 4, healthcare: 4, language: 2, climate: 4, nature: 5, water: 4, family: 2, visaEase: 3, taxes: 2, internet: 3, work: 3, community: 3, pace: 5, housing: 4, food: 5 }), fits: "Pace, food, and villages selling houses for very little.", watch: "Bureaucracy is famous for a reason. Italian is required for daily life. Remote-work visa is new and slow.", path: "Elective residence visa (needs passive income) or the digital nomad visa." },
  { key: "ireland", name: "Ireland", kind: "country", line: "English-speaking, deeply Christian in heritage, green, wet, and expensive to house.", ratings: r({ cost: 2, safety: 4, faithCommunity: 4, religiousFreedom: 5, governmentReach: 3, transit: 3, healthcare: 3, language: 5, climate: 2, nature: 5, water: 5, family: 3, visaEase: 2, taxes: 2, internet: 4, work: 3, community: 4, pace: 4, housing: 1, food: 3 }), fits: "No language barrier, coast on every side, warm people.", watch: "The housing shortage is severe. No easy long-stay visa for Americans without a job offer or Irish ancestry.", path: "Only with a work permit, Irish citizenship by descent, or the Stamp 0 for people with independent means." },
  { key: "costaRica", name: "Costa Rica", kind: "country", line: "Stable, no army, warm, water on two coasts, and a well-worn path for Americans.", ratings: r({ cost: 3, safety: 3, faithCommunity: 5, religiousFreedom: 5, governmentReach: 3, transit: 2, healthcare: 4, language: 3, climate: 4, nature: 5, water: 5, family: 4, visaEase: 4, taxes: 4, internet: 3, work: 4, community: 4, pace: 5, housing: 3, food: 3 }), fits: "Faith community, nature, water, and a few hours from the US.", watch: "Petty theft is common; the cost of living has risen in expat areas. Roads and infrastructure are rough outside the center. Only foreign income is untaxed.", path: "Rentista (proof of income) or digital nomad visa, then residency." },
  { key: "panama", name: "Panama", kind: "country", line: "Dollar economy, tax-friendly, a famously easy residency, and hot all year.", ratings: r({ cost: 3, safety: 3, faithCommunity: 4, religiousFreedom: 5, governmentReach: 3, transit: 2, healthcare: 3, language: 2, climate: 2, nature: 4, water: 5, family: 4, visaEase: 5, taxes: 5, internet: 3, work: 4, community: 3, pace: 4, housing: 3, food: 3 }), fits: "The easiest residency in the region for Americans, uses the US dollar, no tax on foreign income.", watch: "Heat and humidity. Spanish needed outside the capital. The capital is expensive.", path: "Friendly Nations visa (Americans qualify) with a bank deposit or job, or the pensionado for retirees." },
  { key: "mexico", name: "Mexico", kind: "country", line: "Close to family, cheap, warm, with strong Christian culture and big differences by region.", ratings: r({ cost: 5, safety: 2, faithCommunity: 5, religiousFreedom: 5, governmentReach: 3, transit: 3, healthcare: 4, language: 3, climate: 4, nature: 4, water: 4, family: 5, visaEase: 4, taxes: 3, internet: 3, work: 4, community: 4, pace: 4, housing: 4, food: 5 }), fits: "Cost, closeness, faith, and food. Some regions (Yucatán, the highlands) are far safer than the headlines.", watch: "Safety varies enormously by state; choose the region, not the country. Learn Spanish.", path: "Temporary resident visa on proof of income, then permanent residency after four years." },
  { key: "uruguay", name: "Uruguay", kind: "country", line: "The quiet, stable, secular democracy of South America, with beaches and a slow pace.", ratings: r({ cost: 3, safety: 4, faithCommunity: 2, religiousFreedom: 5, governmentReach: 4, transit: 3, healthcare: 4, language: 2, climate: 3, nature: 4, water: 5, family: 1, visaEase: 4, taxes: 4, internet: 4, work: 3, community: 3, pace: 5, housing: 3, food: 3 }), fits: "Stability, coast, and a straightforward residency.", watch: "Far from family. Mostly secular; fewer churches. Spanish needed.", path: "Apply for residency after arriving; proof of income required." },
  { key: "newZealand", name: "New Zealand", kind: "country", line: "Stunning, safe, English-speaking, far from everything, and hard to get into.", ratings: r({ cost: 2, safety: 5, faithCommunity: 3, religiousFreedom: 5, governmentReach: 2, transit: 3, healthcare: 4, language: 5, climate: 3, nature: 5, water: 5, family: 1, visaEase: 2, taxes: 3, internet: 4, work: 3, community: 4, pace: 4, housing: 1, food: 3 }), fits: "Nature and water beyond compare, English, safety.", watch: "Housing is among the least affordable anywhere. Visas need a skilled job offer. A full day's flight from family.", path: "Skilled work visa with a job offer, or the Active Investor visa." },
  { key: "canada", name: "Canada", kind: "country", line: "Next door, English, lakes everywhere, and an immigration system built on points.", ratings: r({ cost: 2, safety: 4, faithCommunity: 3, religiousFreedom: 4, governmentReach: 2, transit: 3, healthcare: 3, language: 5, climate: 2, nature: 5, water: 5, family: 5, visaEase: 3, taxes: 2, internet: 4, work: 3, community: 3, pace: 3, housing: 1, food: 3 }), fits: "Closeness, water, no language barrier.", watch: "Cold. Housing in the cities is out of reach. Points favor younger, credentialed applicants. Healthcare waits are long.", path: "Express Entry (points), a provincial nominee program, or a work permit." },
  { key: "netherlands", name: "Netherlands", kind: "country", line: "Bikes, trains, water everywhere, English spoken by nearly everyone, and a special treaty visa for Americans starting a business.", ratings: r({ cost: 2, safety: 5, faithCommunity: 3, religiousFreedom: 5, governmentReach: 3, transit: 5, healthcare: 4, language: 5, climate: 2, nature: 3, water: 5, family: 2, visaEase: 4, taxes: 2, internet: 5, work: 4, community: 3, pace: 3, housing: 1, food: 3 }), fits: "The DAFT treaty lets an American start a small business and live there with a modest investment. Water and transit are unmatched.", watch: "Housing is scarce and expensive. Grey winters. High taxes. Dutch reserve takes time to get past.", path: "The Dutch-American Friendship Treaty (DAFT) residence permit for self-employed Americans." },
  { key: "poland", name: "Poland", kind: "country", line: "Cheap, safe, deeply Christian, and growing fast; less English, colder winters.", ratings: r({ cost: 5, safety: 5, faithCommunity: 5, religiousFreedom: 5, governmentReach: 3, transit: 4, healthcare: 3, language: 2, climate: 2, nature: 4, water: 3, family: 2, visaEase: 3, taxes: 3, internet: 5, work: 3, community: 3, pace: 3, housing: 4, food: 4 }), fits: "Faith in public life, safety, cost, and excellent internet.", watch: "Polish is hard. Winters are long. The path needs a work or business basis.", path: "A business-activity residence permit, or a work permit." },
  { key: "greece", name: "Greece", kind: "country", line: "Islands and coast, an Orthodox Christian culture, low cost outside Athens, and a digital nomad visa.", ratings: r({ cost: 4, safety: 4, faithCommunity: 4, religiousFreedom: 4, governmentReach: 3, transit: 3, healthcare: 3, language: 3, climate: 5, nature: 5, water: 5, family: 2, visaEase: 4, taxes: 3, internet: 3, work: 3, community: 3, pace: 5, housing: 4, food: 5 }), fits: "Water, sun, pace, and faith visible everywhere.", watch: "Bureaucracy and slow services. Greek is hard; English is fine on the islands. Healthcare is uneven outside cities.", path: "Digital nomad visa or the financially independent person visa." },
  { key: "malta", name: "Malta", kind: "country", line: "A small Catholic island where English is official, warm all year, and busy.", ratings: r({ cost: 2, safety: 5, faithCommunity: 4, religiousFreedom: 5, governmentReach: 3, transit: 3, healthcare: 4, language: 5, climate: 5, nature: 2, water: 5, family: 2, visaEase: 4, taxes: 3, internet: 4, work: 4, community: 3, pace: 3, housing: 2, food: 3 }), fits: "English, faith, water, and a nomad residence permit.", watch: "Crowded, small, and housing costs have climbed. Little nature beyond the sea.", path: "Nomad Residence Permit for remote workers." },
  { key: "czechia", name: "Czechia", kind: "country", line: "Beautiful, safe, cheap, central to Europe, and one of the least religious countries on earth.", ratings: r({ cost: 4, safety: 5, faithCommunity: 1, religiousFreedom: 5, governmentReach: 3, transit: 5, healthcare: 4, language: 2, climate: 2, nature: 4, water: 3, family: 2, visaEase: 3, taxes: 3, internet: 5, work: 4, community: 3, pace: 3, housing: 3, food: 3 }), fits: "Safety, trains, cost, a long-established path for freelancers.", watch: "Finding church community will take work. Czech is hard. Grey winters.", path: "The trade license (živnostenské oprávnění) long-stay visa for freelancers." },
  // US states, for the stay-and-move option
  { key: "tennessee", name: "Tennessee", kind: "state", line: "No state income tax, low cost, church on every corner, lakes and rivers, and hot summers.", ratings: r({ cost: 4, safety: 3, faithCommunity: 5, religiousFreedom: 5, governmentReach: 4, transit: 1, healthcare: 3, language: 5, climate: 3, nature: 4, water: 4, family: 4, visaEase: 5, taxes: 5, internet: 4, work: 4, community: 4, pace: 4, housing: 3, food: 4 }), fits: "Faith, cost, water, and no state income tax.", watch: "You'll need two cars. Summers are heavy. Nashville has gotten pricey; look at the smaller towns near water.", path: "Just move. Update your license and registration within 30 days." },
  { key: "northCarolina", name: "North Carolina", kind: "state", line: "Mountains and coast in one state, mild seasons, strong churches, moderate cost.", ratings: r({ cost: 3, safety: 3, faithCommunity: 5, religiousFreedom: 5, governmentReach: 3, transit: 2, healthcare: 3, language: 5, climate: 4, nature: 5, water: 5, family: 4, visaEase: 5, taxes: 3, internet: 4, work: 4, community: 4, pace: 3, housing: 3, food: 3 }), fits: "Water on the coast, mountains inland, faith community everywhere.", watch: "Hurricanes on the coast; growth has raised prices near the cities.", path: "Just move." },
  { key: "florida", name: "Florida", kind: "state", line: "Water everywhere, no state income tax, warm, expensive to insure, and crowded.", ratings: r({ cost: 3, safety: 3, faithCommunity: 4, religiousFreedom: 5, governmentReach: 4, transit: 2, healthcare: 3, language: 5, climate: 3, nature: 4, water: 5, family: 4, visaEase: 5, taxes: 5, internet: 4, work: 4, community: 3, pace: 3, housing: 2, food: 4 }), fits: "Water, warmth, no state income tax.", watch: "Home insurance and hurricanes. Heat and humidity for half the year. Housing has climbed.", path: "Just move." },
  { key: "idaho", name: "Idaho", kind: "state", line: "Rivers, mountains, small towns, low reach of government, and long winters.", ratings: r({ cost: 3, safety: 5, faithCommunity: 4, religiousFreedom: 5, governmentReach: 5, transit: 1, healthcare: 3, language: 5, climate: 2, nature: 5, water: 4, family: 3, visaEase: 5, taxes: 4, internet: 3, work: 3, community: 3, pace: 5, housing: 3, food: 2 }), fits: "Safety, nature, water, and being left alone.", watch: "Winters are real. Healthcare is thin outside Boise. Housing rose fast after 2020.", path: "Just move." },
  { key: "texas", name: "Texas", kind: "state", line: "Big, cheap-ish, no state income tax, strong churches, hot, and car-dependent.", ratings: r({ cost: 4, safety: 3, faithCommunity: 5, religiousFreedom: 5, governmentReach: 4, transit: 2, healthcare: 3, language: 5, climate: 2, nature: 3, water: 3, family: 4, visaEase: 5, taxes: 5, internet: 4, work: 5, community: 4, pace: 3, housing: 3, food: 5 }), fits: "Business-friendly, faith community, cost, food.", watch: "Heat, property taxes, sprawl, and a fragile power grid.", path: "Just move." },
  { key: "vermont", name: "Vermont", kind: "state", line: "Green, quiet, lakes, small towns, cold, expensive, and secular.", ratings: r({ cost: 2, safety: 5, faithCommunity: 2, religiousFreedom: 5, governmentReach: 2, transit: 1, healthcare: 4, language: 5, climate: 2, nature: 5, water: 4, family: 3, visaEase: 5, taxes: 2, internet: 3, work: 3, community: 4, pace: 5, housing: 2, food: 3 }), fits: "Pace, safety, nature, water.", watch: "Long winters, high taxes, few churches, housing is tight.", path: "Just move." },
];

export const SOURCES: { name: string; what: string; url: string }[] = [
  { name: "Numbeo", what: "Cost of living and crime, city by city, from residents.", url: "https://www.numbeo.com" },
  { name: "US State Department travel advisories", what: "Safety level per country, updated often.", url: "https://travel.state.gov" },
  { name: "Pew Research religious composition", what: "Religious demographics by country.", url: "https://www.pewresearch.org" },
  { name: "Freedom House", what: "Political rights and civil liberties scores.", url: "https://freedomhouse.org" },
  { name: "Numbeo Health Care Index", what: "Healthcare quality as rated by residents.", url: "https://www.numbeo.com/health-care/" },
  { name: "Each country's consulate", what: "The visa that actually applies to you, with current fees and income thresholds.", url: "https://travel.state.gov" },
];
