import type { Ref } from "./refs";

/**
 * "Where am I?": one plain card per book. Who wrote it, to whom, why, and
 * how it points to Jesus. Written to be read in thirty seconds by someone
 * who has heard all the churchy versions and needs the plain one.
 */
export interface BookGuide {
  slug: string;
  who: string;
  toWhom: string;
  why: string;
  jesus: string;
  /** A good first chapter to open. */
  start: Ref;
}

export const BOOK_GUIDES: BookGuide[] = [
  { slug: "genesis", who: "Traditionally Moses, from older stories.", toWhom: "Israel, learning who their God is.", why: "Where everything came from: the world, people, the mess, and the promise that God would fix it through one family.", jesus: "The promise to Abraham that all peoples would be blessed through his line is the first thread that leads to Jesus.", start: { book: "genesis", chapter: 1 } },
  { slug: "exodus", who: "Traditionally Moses.", toWhom: "A people who had just been rescued from slavery.", why: "God hears the cry of enslaved people, gets them out, and makes a home with them.", jesus: "Jesus is called the true Passover lamb; the rescue from Egypt is the pattern for the rescue he brings.", start: { book: "exodus", chapter: 3 } },
  { slug: "leviticus", who: "Traditionally Moses.", toWhom: "Priests and people learning to live near a holy God.", why: "How a people could be close to God without being destroyed by the difference; the sacrifices carry that weight.", jesus: "Hebrews reads the whole system as a picture Jesus fulfilled once, for good.", start: { book: "leviticus", chapter: 19 } },
  { slug: "numbers", who: "Traditionally Moses.", toWhom: "Israel in the wilderness.", why: "Forty years of wandering, complaining, and God staying anyway.", jesus: "Jesus points to the bronze snake lifted up in Numbers 21 as a picture of his own lifting up.", start: { book: "numbers", chapter: 6 } },
  { slug: "deuteronomy", who: "Traditionally Moses, in his last speeches.", toWhom: "The next generation, about to enter the land.", why: "Remember who rescued you; love God with everything; choose life.", jesus: "Jesus quoted Deuteronomy in the wilderness to every temptation, and called 'love the Lord your God' the greatest command.", start: { book: "deuteronomy", chapter: 6 } },
  { slug: "joshua", who: "Unknown, drawing on Joshua's records.", toWhom: "Israel, settling the land.", why: "God keeps the promise of a home; courage comes from his presence, not from strength.", jesus: "Joshua and Jesus share a name, 'the Lord saves'; one led into a land, the other into rest.", start: { book: "joshua", chapter: 1 } },
  { slug: "judges", who: "Unknown.", toWhom: "Israel, looking back at a chaotic time.", why: "A cycle: people drift, get hurt, cry out, God sends a rescuer, repeat. Honest about how messy rescuers were.", jesus: "Every flawed judge leaves you wanting a rescuer who won't fail. That longing is answered in Jesus.", start: { book: "judges", chapter: 6 } },
  { slug: "ruth", who: "Unknown.", toWhom: "Anyone who thinks outsiders don't belong.", why: "A foreign widow's loyalty, and a kind man who takes her in; ordinary faithfulness in a bad season.", jesus: "Ruth is in Jesus' family tree. Boaz redeeming her is a small picture of what Jesus does.", start: { book: "ruth", chapter: 1 } },
  { slug: "1-samuel", who: "Unknown, from prophetic records.", toWhom: "Israel, remembering how kings began.", why: "Samuel, Saul, and David: what God looks at (the heart) and what people look at (the outside).", jesus: "David, the shepherd king, is the pattern for the King Jesus is.", start: { book: "1-samuel", chapter: 16 } },
  { slug: "2-samuel", who: "Unknown.", toWhom: "Israel, remembering David.", why: "David at his best and his worst, and God's promise that his line would last forever.", jesus: "The promise in chapter 7 of a son of David who reigns forever is a promise about Jesus.", start: { book: "2-samuel", chapter: 7 } },
  { slug: "1-kings", who: "Unknown, from court records and prophets' stories.", toWhom: "Israel in exile, asking how it went wrong.", why: "Solomon's wisdom and folly, the kingdom splitting, and Elijah standing alone.", jesus: "Jesus called himself greater than Solomon and greater than the temple.", start: { book: "1-kings", chapter: 19 } },
  { slug: "2-kings", who: "Unknown.", toWhom: "Israel in exile.", why: "The slow slide of both kingdoms, with a few bright kings and prophets along the way.", jesus: "The exile leaves the question hanging: who will bring us home? The Gospels answer it.", start: { book: "2-kings", chapter: 5 } },
  { slug: "1-chronicles", who: "Traditionally Ezra or someone near him.", toWhom: "People rebuilding after exile.", why: "The same story as Samuel and Kings, retold to say: you still belong to this family and this promise.", jesus: "The long family lists end up in Matthew 1, in Jesus.", start: { book: "1-chronicles", chapter: 17 } },
  { slug: "2-chronicles", who: "Traditionally Ezra or someone near him.", toWhom: "People rebuilding after exile.", why: "Kings, the temple, and the repeated invitation: if my people humble themselves, I will hear.", jesus: "The temple at the center of this book is what Jesus said his own body was.", start: { book: "2-chronicles", chapter: 7 } },
  { slug: "ezra", who: "Ezra, a scribe.", toWhom: "The returned exiles.", why: "Coming home and rebuilding, with all the setbacks that involves.", jesus: "A return from exile that is real but incomplete; Jesus brings the fuller one.", start: { book: "ezra", chapter: 3 } },
  { slug: "nehemiah", who: "Nehemiah, a governor.", toWhom: "The returned exiles.", why: "Rebuilding a wall and a people while being mocked and threatened; prayer and work side by side.", jesus: "Nehemiah's grief for his city echoes Jesus weeping over Jerusalem.", start: { book: "nehemiah", chapter: 1 } },
  { slug: "esther", who: "Unknown.", toWhom: "Jews living far from home.", why: "God's name is never mentioned, and his hand is everywhere. Courage 'for such a time as this.'", jesus: "A rescue that comes through someone willing to risk everything for their people.", start: { book: "esther", chapter: 4 } },
  { slug: "job", who: "Unknown.", toWhom: "Anyone who has suffered and been told it was their fault.", why: "Job's friends explain his pain with tidy religion. God rejects their explanations and speaks to Job himself.", jesus: "Job longs for someone to stand between him and God. Jesus is that someone.", start: { book: "job", chapter: 38 } },
  { slug: "psalms", who: "David and many others, over centuries.", toWhom: "Everyone who needs words for God.", why: "Songs for every state: joy, rage, fear, doubt, gratitude, despair. Nothing is too raw to bring.", jesus: "Jesus prayed the Psalms, including 'My God, why have you forsaken me' from the cross.", start: { book: "psalms", chapter: 23 } },
  { slug: "proverbs", who: "Solomon and other sages.", toWhom: "Young people learning how life works.", why: "Wisdom for ordinary days: money, words, anger, work, friends. General patterns, not promises.", jesus: "Wisdom is personified in chapter 8; the New Testament calls Jesus the wisdom of God.", start: { book: "proverbs", chapter: 3 } },
  { slug: "ecclesiastes", who: "'The Teacher,' traditionally Solomon.", toWhom: "Anyone who has tried everything and still feels empty.", why: "Honest about how little adds up under the sun, and how to live anyway: eat, work, love, fear God.", jesus: "The emptiness it names is the hunger Jesus offers to fill.", start: { book: "ecclesiastes", chapter: 3 } },
  { slug: "song-of-solomon", who: "Traditionally Solomon.", toWhom: "Lovers.", why: "A love poem. Desire and delight between two people, with no apology.", jesus: "Many have read it as a picture of God's delight in his people.", start: { book: "song-of-solomon", chapter: 2 } },
  { slug: "isaiah", who: "Isaiah, a prophet in Jerusalem.", toWhom: "Judah under threat, and exiles far ahead.", why: "Judgment for injustice, and then comfort: a servant who suffers for others, a new creation.", jesus: "Isaiah 53's suffering servant is the passage the first Christians read as Jesus' story.", start: { book: "isaiah", chapter: 53 } },
  { slug: "jeremiah", who: "Jeremiah, with his scribe Baruch.", toWhom: "Judah in its last years before exile.", why: "A prophet who wept, was ignored, and kept telling the truth. Also: a new covenant written on hearts.", jesus: "Jesus lifted the cup and called it the new covenant Jeremiah promised.", start: { book: "jeremiah", chapter: 31 } },
  { slug: "lamentations", who: "Traditionally Jeremiah.", toWhom: "A city in ruins.", why: "Grief with no rush to fix it. In the middle: 'his mercies are new every morning.'", jesus: "Jesus wept over the same city. Grief is allowed.", start: { book: "lamentations", chapter: 3 } },
  { slug: "ezekiel", who: "Ezekiel, a priest in exile.", toWhom: "Exiles in Babylon.", why: "Strange visions, hard words, and then hope: dry bones living, a new heart, God as shepherd.", jesus: "Jesus called himself the good shepherd Ezekiel 34 promised.", start: { book: "ezekiel", chapter: 34 } },
  { slug: "daniel", who: "Daniel, in exile.", toWhom: "Jews living under empires.", why: "Faithfulness under pressure, and visions that empires don't get the last word.", jesus: "'Son of Man' in Daniel 7 is the name Jesus used for himself most.", start: { book: "daniel", chapter: 3 } },
  { slug: "hosea", who: "Hosea, a prophet.", toWhom: "Israel, unfaithful.", why: "God tells a prophet to love a wife who keeps leaving, to show what God's love is like.", jesus: "Matthew quotes Hosea: 'Out of Egypt I called my son.'", start: { book: "hosea", chapter: 11 } },
  { slug: "joel", who: "Joel, a prophet.", toWhom: "Judah after a locust plague.", why: "Disaster, a call to return, and a promise: God's Spirit poured out on everyone.", jesus: "Peter quoted Joel at Pentecost to explain what Jesus had just sent.", start: { book: "joel", chapter: 2 } },
  { slug: "amos", who: "Amos, a shepherd.", toWhom: "Comfortable, religious, unjust Israel.", why: "God hates worship that ignores the poor. 'Let justice roll down like water.'", jesus: "Jesus' anger at religion that crushes people comes from the same place.", start: { book: "amos", chapter: 5 } },
  { slug: "obadiah", who: "Obadiah.", toWhom: "Edom, Israel's neighbor.", why: "One chapter: pride and gloating over a brother's fall will be judged.", jesus: "The kingdom belongs to the Lord, which Jesus announced.", start: { book: "obadiah", chapter: 1 } },
  { slug: "jonah", who: "Unknown.", toWhom: "People who don't want God to be kind to their enemies.", why: "A prophet runs from mercy, and God is kind to a city Jonah hates.", jesus: "Jesus called his death and rising 'the sign of Jonah.'", start: { book: "jonah", chapter: 4 } },
  { slug: "micah", who: "Micah, a prophet.", toWhom: "Judah and Israel.", why: "Injustice named, and the plainest summary: do justice, love mercy, walk humbly.", jesus: "Micah 5 names Bethlehem as the birthplace of the ruler to come.", start: { book: "micah", chapter: 6 } },
  { slug: "nahum", who: "Nahum, a prophet.", toWhom: "Judah, about Nineveh.", why: "A cruel empire will fall. God is slow to anger and does not leave cruelty unanswered.", jesus: "Good news to the oppressed, which Jesus said he came to bring.", start: { book: "nahum", chapter: 1 } },
  { slug: "habakkuk", who: "Habakkuk, a prophet.", toWhom: "Himself and God, in an argument.", why: "'How long?' A prophet complains to God, listens, and ends up trusting in the dark.", jesus: "'The righteous will live by faith' became Paul's summary of the gospel.", start: { book: "habakkuk", chapter: 3 } },
  { slug: "zephaniah", who: "Zephaniah, a prophet.", toWhom: "Judah.", why: "The day of the Lord, and then: God rejoicing over his people with singing.", jesus: "The God who sings over you is the Father Jesus described.", start: { book: "zephaniah", chapter: 3 } },
  { slug: "haggai", who: "Haggai, a prophet.", toWhom: "Returned exiles who had stalled.", why: "Build the house; God is with you; the glory to come is greater than what was lost.", jesus: "The greater glory arrived when Jesus walked into that temple.", start: { book: "haggai", chapter: 2 } },
  { slug: "zechariah", who: "Zechariah, a prophet.", toWhom: "Returned exiles.", why: "Visions of restoration and a king coming humble, on a donkey.", jesus: "Palm Sunday is Zechariah 9 acted out on purpose.", start: { book: "zechariah", chapter: 9 } },
  { slug: "malachi", who: "Malachi, a prophet.", toWhom: "Tired, half-hearted worshipers.", why: "God argues with a people who have stopped expecting anything, and promises a messenger.", jesus: "The messenger is John the Baptist; the one he prepares for is Jesus.", start: { book: "malachi", chapter: 3 } },
  { slug: "matthew", who: "Matthew, a tax collector Jesus called.", toWhom: "Jewish readers who knew the promises.", why: "Jesus as the promised King, teaching on the mountain, gathering a people.", jesus: "This is Jesus, told by someone who was there.", start: { book: "matthew", chapter: 5 } },
  { slug: "mark", who: "Mark, from Peter's memories.", toWhom: "Roman readers, in a hurry.", why: "The shortest, fastest Gospel. Jesus acts more than he explains. Start here if you're new.", jesus: "This is Jesus, told fast.", start: { book: "mark", chapter: 1 } },
  { slug: "luke", who: "Luke, a doctor and careful researcher.", toWhom: "Theophilus, and anyone on the outside.", why: "Jesus with the poor, women, outsiders, and the lost. The most stories about mercy.", jesus: "This is Jesus, told by someone who interviewed the witnesses.", start: { book: "luke", chapter: 15 } },
  { slug: "john", who: "John, 'the disciple Jesus loved.'", toWhom: "Anyone deciding what to make of Jesus.", why: "Long conversations, seven signs, and 'I am' sayings. Written 'so that you may believe.'", jesus: "This is Jesus, told by his closest friend, decades later, still amazed.", start: { book: "john", chapter: 4 } },
  { slug: "acts", who: "Luke.", toWhom: "Theophilus.", why: "What Jesus' people did next: the Spirit comes, the message spreads, Paul is converted.", jesus: "Jesus keeps working, now through ordinary people.", start: { book: "acts", chapter: 2 } },
  { slug: "romans", who: "Paul.", toWhom: "Christians in Rome he hadn't met.", why: "The fullest explanation of the gospel: everyone has fallen short, everyone is offered grace, nothing can separate you.", jesus: "Righteousness comes as a gift through Jesus, not as a wage for religion.", start: { book: "romans", chapter: 8 } },
  { slug: "1-corinthians", who: "Paul.", toWhom: "A messy, gifted, divided church.", why: "Practical problems, love as the highest way, and the resurrection as the whole point.", jesus: "'If Christ has not been raised, our faith is useless.' Everything hangs on Jesus alive.", start: { book: "1-corinthians", chapter: 13 } },
  { slug: "2-corinthians", who: "Paul.", toWhom: "The same church, after a painful visit.", why: "Paul's most personal letter: weakness, comfort, and 'my grace is sufficient for you.'", jesus: "God's power shows up in weakness, which is the shape of the cross.", start: { book: "2-corinthians", chapter: 12 } },
  { slug: "galatians", who: "Paul.", toWhom: "Churches being told they needed rules on top of Jesus.", why: "Freedom. You are not saved by keeping religion; don't let anyone put the yoke back on.", jesus: "'It is for freedom that Christ has set us free.'", start: { book: "galatians", chapter: 5 } },
  { slug: "ephesians", who: "Paul.", toWhom: "Churches around Ephesus.", why: "Who you are in Christ, chosen and loved, and how that shapes a home and a community.", jesus: "'By grace you have been saved through faith, not by works.'", start: { book: "ephesians", chapter: 2 } },
  { slug: "philippians", who: "Paul, from prison.", toWhom: "A church he loved.", why: "Joy in a cell. Jesus emptied himself; don't be anxious; think on what is good.", jesus: "The hymn in chapter 2 is the clearest picture of Jesus' humility.", start: { book: "philippians", chapter: 4 } },
  { slug: "colossians", who: "Paul.", toWhom: "A church tempted by add-ons and rules.", why: "Jesus is enough; he holds everything together; don't let anyone judge you by rules.", jesus: "Jesus is the image of the invisible God.", start: { book: "colossians", chapter: 1 } },
  { slug: "1-thessalonians", who: "Paul.", toWhom: "A young church under pressure.", why: "Encouragement, hope for those who died, and 'pray continually.'", jesus: "Jesus will return; grief has hope in it.", start: { book: "1-thessalonians", chapter: 4 } },
  { slug: "2-thessalonians", who: "Paul.", toWhom: "The same church, confused about the end.", why: "Keep going; don't be shaken; work quietly.", jesus: "Jesus will set things right; you don't have to.", start: { book: "2-thessalonians", chapter: 3 } },
  { slug: "1-timothy", who: "Paul.", toWhom: "Timothy, a young leader.", why: "How to lead and care for a church; godliness with contentment.", jesus: "'Christ Jesus came into the world to save sinners, of whom I am the worst.'", start: { book: "1-timothy", chapter: 1 } },
  { slug: "2-timothy", who: "Paul, near death.", toWhom: "Timothy, his son in the faith.", why: "Last words: guard the good deposit, endure, the Scriptures are breathed by God.", jesus: "'If we are faithless, he remains faithful.'", start: { book: "2-timothy", chapter: 1 } },
  { slug: "titus", who: "Paul.", toWhom: "Titus, leading churches on Crete.", why: "Grace teaches us how to live; good works flow from kindness received.", jesus: "'He saved us, not because of righteous things we had done, but because of his mercy.'", start: { book: "titus", chapter: 3 } },
  { slug: "philemon", who: "Paul.", toWhom: "Philemon, a slave owner, about Onesimus.", why: "One page: welcome him back as a brother, and charge anything he owes to me.", jesus: "Paul does for Onesimus what Jesus does for us.", start: { book: "philemon", chapter: 1 } },
  { slug: "hebrews", who: "Unknown.", toWhom: "Jewish Christians tempted to go back.", why: "Jesus is greater than angels, Moses, priests, and sacrifices; he is the high priest who understands weakness.", jesus: "'We do not have a high priest who is unable to sympathize with our weaknesses.'", start: { book: "hebrews", chapter: 4 } },
  { slug: "james", who: "James, Jesus' brother.", toWhom: "Scattered Christians.", why: "Faith you can see: patience, the tongue, care for the poor, honest prayer.", jesus: "Much of James echoes Jesus' own teaching on the mountain.", start: { book: "james", chapter: 1 } },
  { slug: "1-peter", who: "Peter.", toWhom: "Christians suffering as outsiders.", why: "You are chosen and precious; suffer well; cast your anxiety on him because he cares for you.", jesus: "Jesus suffered and left an example; his wounds heal.", start: { book: "1-peter", chapter: 5 } },
  { slug: "2-peter", who: "Peter, near death.", toWhom: "The same churches.", why: "Remember what you were taught; the Lord is patient, not slow.", jesus: "Grow in the grace and knowledge of Jesus.", start: { book: "2-peter", chapter: 1 } },
  { slug: "1-john", who: "John, as an old man.", toWhom: "Churches unsettled by false teachers.", why: "God is light; God is love; perfect love drives out fear; you can know you have life.", jesus: "'This is love: not that we loved God, but that he loved us and sent his Son.'", start: { book: "1-john", chapter: 4 } },
  { slug: "2-john", who: "John.", toWhom: "A church he calls 'the chosen lady.'", why: "One page: walk in love and truth; don't welcome what denies Jesus.", jesus: "Love and truth, held together, as Jesus held them.", start: { book: "2-john", chapter: 1 } },
  { slug: "3-john", who: "John.", toWhom: "Gaius, a friend.", why: "One page: thank you for your hospitality; watch out for the man who loves to be first.", jesus: "Kindness to strangers is kindness to Jesus.", start: { book: "3-john", chapter: 1 } },
  { slug: "jude", who: "Jude, Jesus' brother.", toWhom: "Christians facing people who twisted grace.", why: "Contend for the faith; and a blessing: he is able to keep you from stumbling.", jesus: "'To him who is able to keep you from falling and present you faultless.'", start: { book: "jude", chapter: 1 } },
  { slug: "revelation", who: "John, exiled on Patmos.", toWhom: "Seven churches under Rome.", why: "Visions to comfort persecuted people: the Lamb wins, evil ends, God wipes every tear.", jesus: "Jesus as the Lamb who was slain and is worthy; the end is a wedding, not a war.", start: { book: "revelation", chapter: 21 } },
];

export function guideFor(slug: string): BookGuide | undefined {
  return BOOK_GUIDES.find((g) => g.slug === slug);
}
