/** Churchy words, in plain words. For people who know all the words and are tired of them. */
export const GLOSSARY: { term: string; plain: string }[] = [
  { term: "Gospel", plain: "Good news. The announcement that Jesus lived, died, and rose, and that this changes everything, before you do anything." },
  { term: "Grace", plain: "Being given what you didn't earn and couldn't. Kindness with no invoice." },
  { term: "Sin", plain: "Missing the mark; the ways we hurt ourselves, each other, and God. A description, not a life sentence." },
  { term: "Repentance", plain: "Turning around. A change of mind that turns into a change of direction. Not groveling." },
  { term: "Righteousness", plain: "Being right with God and living rightly with people. In the New Testament, given as a gift, not achieved." },
  { term: "Justification", plain: "Being declared right with God because of Jesus, like a verdict, not a grade." },
  { term: "Sanctification", plain: "Slowly becoming more like Jesus over a lifetime. Slow is the design." },
  { term: "Salvation", plain: "Being rescued. From death, from sin, from yourself, into life with God." },
  { term: "Covenant", plain: "A binding promise between God and people, more like a marriage than a contract." },
  { term: "Atonement", plain: "Being made 'at one' with God again. What Jesus' death accomplishes." },
  { term: "Redemption", plain: "Being bought back, like a person freed from slavery by someone who paid." },
  { term: "Holy", plain: "Set apart, wholly other, and wholly good. Not 'strict.'" },
  { term: "Faith", plain: "Trust. Leaning your weight on someone. Not certainty, and not a feeling you have to manufacture." },
  { term: "Kingdom of God", plain: "Wherever God's way is done. Jesus said it had come near in him." },
  { term: "Abide", plain: "Stay. Remain. Make your home in. What a branch does in a vine." },
  { term: "Disciple", plain: "A learner who follows a teacher around. Apprentice." },
  { term: "Apostle", plain: "Someone sent out with a message. The first ones had seen Jesus alive." },
  { term: "Pharisee", plain: "A religious group in Jesus' day, serious about rules. Some were sincere; the ones Jesus fought used rules to crush people." },
  { term: "Sabbath", plain: "A weekly day of rest, made for people. Jesus healed on it on purpose." },
  { term: "Messiah / Christ", plain: "The anointed one, the promised King. 'Christ' is a title, not a surname." },
  { term: "Son of Man", plain: "Jesus' favorite name for himself, from Daniel 7: a human figure given God's authority." },
  { term: "Incarnation", plain: "God becoming a human being, with skin, hunger, and tiredness." },
  { term: "Resurrection", plain: "Jesus physically alive again after being dead. The center of everything." },
  { term: "Holy Spirit", plain: "God present with and in people. Jesus called him the Helper." },
  { term: "Trinity", plain: "One God, known as Father, Son, and Spirit. Christians have always found it hard to explain and true." },
  { term: "Communion / Lord's Supper", plain: "Bread and wine shared to remember Jesus' body and blood. He started it at a dinner." },
  { term: "Baptism", plain: "Going under water and coming up, a picture of dying and rising with Jesus." },
  { term: "Conviction", plain: "The Spirit showing you something true so you can turn; it feels like clarity, not crushing. Shame is not conviction." },
  { term: "Backsliding", plain: "A word churches use for drifting. Jesus' word for the drifter was 'son,' and the father ran." },
  { term: "Quiet time", plain: "A church phrase for reading and praying daily. Not in the Bible. Jesus went off alone when he could; there was no chart." },
  { term: "Lament", plain: "Grief and complaint addressed to God. A third of the Psalms. Allowed." },
  { term: "Epistle", plain: "A letter. Most of the New Testament is mail." },
  { term: "Prophet", plain: "Someone who speaks for God, usually to power, usually unwelcome. More truth-telling than fortune-telling." },
  { term: "Law (Torah)", plain: "The first five books, and God's instructions in them. Given to a rescued people, not as the way to get rescued." },
  { term: "Glory", plain: "The weight and brightness of who God is. Jesus showed it by washing feet." },
];
