"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";

interface FAQItem {
  question: string;
  answer: string;
}

const FAQS: FAQItem[] = [
  {
    question: "How does SnipFlow work?",
    answer:
      "You paste a YouTube link or upload an MP4 video. SnipFlow transcribes the audio using AI (Deepgram), then Claude AI identifies the 5 most quotable/engaging moments. For each moment, it generates a LinkedIn post (150-200 words), a Twitter/X thread (5 tweets), and a TikTok caption (3 sentences + 5 hashtags). You can view everything on screen, and after payment, download the entire pack as a .zip file with organized .txt files for each platform.",
  },
  {
    question: "What types of videos work best?",
    answer:
      "SnipFlow works best with webinar recordings, long-form educational content, podcast episodes, keynote speeches, product demos, and training sessions — anything where you share insights or value over 10+ minutes. The AI is optimized to find quotable moments and actionable takeaways. Short clips under 5 minutes may yield fewer moments.",
  },
  {
    question: "Do I need a credit card to try it?",
    answer:
      "Not at all! You can paste a YouTube URL and process your first video completely free — no login, no credit card. You'll see all the generated content on screen. You only pay when you want to download the full content pack as a .zip file. It's a one-time $49 payment for lifetime access, or $19/month if you prefer monthly billing.",
  },
  {
    question: "Can I try before I buy?",
    answer:
      "Absolutely. Visit our <a href='/demo' class='text-primary hover:underline'>demo page</a> to see a complete sample output from a 45-minute webinar — including LinkedIn posts, Twitter threads, and TikTok captions. You can even download the sample .zip pack. That way you know exactly what you're getting before committing.",
  },
  {
    question: "Is my video data stored securely?",
    answer:
      "Yes. Video uploads are processed in-memory and the audio transcript is stored temporarily for AI processing. Once your content pack is generated, the raw audio file is deleted. Only the transcript and generated content are stored in your account so you can access your packs from the dashboard. We never share your video content with third parties. See our <a href='/refund-policy' class='text-primary hover:underline'>Privacy Policy</a> for full details.",
  },
  {
    question: "What platforms do you support?",
    answer:
      "SnipFlow generates content optimized for LinkedIn (professional posts + carousel scripts), Twitter/X (5-tweet threads with hooks and CTAs), and TikTok (captions with 5 hashtags). You can also choose which platforms to include — just toggle them before downloading.",
  },
  {
    question: "What is the quality of the AI-generated content?",
    answer:
      "The content is generated by Claude 3.5 Sonnet, one of the most advanced language models available. Each piece is tailored to its platform's unique tone — professional for LinkedIn, conversational for Twitter, and punchy for TikTok. Users consistently tell us the tone is 'spot on' (read our testimonials). We recommend reviewing and personalizing posts before publishing, as you would with any AI-assisted tool.",
  },
  {
    question: "Can I upload my own video files?",
    answer:
      "Yes! In addition to YouTube links, you can upload MP4 files directly. The upload limit is 500MB per video. We process the audio, identify the key moments, and generate your content pack — same workflow as YouTube links.",
  },
  {
    question: "What happens after I pay?",
    answer:
      "Once your payment is confirmed ($49 one-time or $19/month), the download button unlocks immediately. You can download your content pack as a .zip file containing organized .txt files for each platform and moment. We also send a confirmation email with a download link. Your packs are always accessible from your dashboard.",
  },
  {
    question: "Can I access my content packs later?",
    answer:
      "Yes. All your content packs are stored in your dashboard (accessible at <a href='/dashboard' class='text-primary hover:underline'>/dashboard</a>). You can view, re-download, or share them at any time. Nothing expires — once you've generated a pack, it's yours forever.",
  },
  {
    question: "Is there a refund policy?",
    answer:
      "Yes. We offer a 14-day money-back guarantee. If SnipFlow isn't the right fit, email us within 14 days of purchase and we'll refund your payment in full — no questions asked. See our <a href='/refund-policy' class='text-primary hover:underline'>Refund Policy</a> for full details.",
  },
  {
    question: "Can I upgrade from monthly to lifetime?",
    answer:
      "Yes. You can upgrade from the $19/month plan to the $49 lifetime plan at any time. The lifetime access is a one-time purchase that never expires. Just reach out via the contact form and we'll help you switch.",
  },
];

export function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="w-full py-12 md:py-24 lg:py-32 border-t border-border">
      <div className="container px-4 md:px-6 mx-auto max-w-3xl">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold tracking-tighter md:text-4xl mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-foreground/70 md:text-lg max-w-2xl mx-auto">
            Everything you need to know about SnipFlow. Still have questions? Reach out and we&apos;ll help.
          </p>
        </div>

        <div className="space-y-3">
          {FAQS.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div
                key={index}
                className="bg-card border border-border rounded-lg overflow-hidden transition-all duration-200 hover:border-primary/30"
              >
                <button
                  onClick={() => toggle(index)}
                  className="w-full flex items-center justify-between px-6 py-4 text-left text-sm font-medium hover:bg-primary/5 transition-colors cursor-pointer"
                  aria-expanded={isOpen}
                >
                  <span className="text-foreground pr-4">{faq.question}</span>
                  {isOpen ? (
                    <ChevronUp className="h-4 w-4 text-primary shrink-0" />
                  ) : (
                    <ChevronDown className="h-4 w-4 text-primary shrink-0" />
                  )}
                </button>
                {isOpen && (
                  <div className="px-6 pb-4">
                    <p
                      className="text-sm text-foreground/70 leading-relaxed"
                      dangerouslySetInnerHTML={{ __html: faq.answer }}
                    />
                  </div>
                )}
              </div>
            );
          })}
        </div>

        <div className="text-center mt-10">
          <p className="text-foreground/60 text-sm">
            Still have questions?{" "}
            <a href="mailto:support@snipflow.com" className="text-primary hover:underline">
              support@snipflow.com
            </a>
          </p>
        </div>
      </div>
    </section>
  );
}