import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npx convex dev`.
    "convex/_generated/**",
    // Heartwood Fitness is its own Vite app with its own tsconfig (scripts/build-heartwood.mjs).
    "heartwood/**",
    "public/fitness/app/**",
  ]),
]);

export default eslintConfig;
